name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make clean all tests
    - name: run utility
      run: ./dmalloc
    - name: run tests
      run: make light heavy
    - name: make distclean
      run: make distclean
    - name: configure in subdir
      run: mkdir x ; cd x ; ../configure
    - name: make in subdir
      run: cd x ; make clean all tests
    - name: run utility in subdir
      run: cd x ; ./dmalloc
    - name: run tests in subdir
      run: cd x ; make light heavy
